### ISSUE TITLE
v1.5 CLI V2 fate flow-client  submit 问题

### ISSUE THREAD

**Issue by Potato-Shy** [FederatedAI/FATE#2466]
当我使用flow job submit 提交人物时，出现以下字段
`{
    "retcode": 100,
    "retmsg": "Connection refused. Please check if the fate flow service is started"
}
`

**Comment by bdfa6c** [comment]
@Potato-Shy The `retmsg` is clear. I think you first need to make sure the server is running, by `ps -ef | grep -i fate_flow_server.py`. Then,
```
cd /data/projects/fate/python/fate_flow
sh service.sh restart
```
Refer to [Fate allinone deployment](https://github.com/FederatedAI/FATE/blob/master/cluster-deploy/doc/Fate-allinone_deployment_guide_install_zh.md)

**Comment by bdfa6c** [comment]
In addition, I feel that `python fate_flow_client.py` is less buggy than `flow`.

**Comment by Potato-Shy** [comment]
> @Potato-Shy The `retmsg` is clear. I think you first need to make sure the server is running, by `ps -ef | grep -i fate_flow_server.py`. Then,
> 
> ```
> cd /data/projects/fate/python/fate_flow
> sh service.sh restart
> ```
> 
> Refer to [Fate allinone deployment](https://github.com/FederatedAI/FATE/blob/master/cluster-deploy/doc/Fate-allinone_deployment_guide_install_zh.md)
很感谢您的回复，但是我进行restart还是会出现这个问题

**Comment by ChangxinBai** [comment]
@bdfa6c 
I also have this issue.
When i executed the command: sh service.sh restart 
I got this information below:
PROJECT_BASE: /data/projects/fate
file not found: /date/projects/fate/bin/init_env.sh
Also, I do not have the /date/projects/fate/bin folder.

Looking forward to your reply. Thanks

**Comment by izhfeng00** [comment]
把conf/service_conf.yaml中fateflow的host配置从“127.0.0.1”修改成真实的ip，再重启服务试试

**Comment by Milkve** [comment]
> @Potato-Shy The `retmsg` is clear. I think you first need to make sure the server is running, by `ps -ef | grep -i fate_flow_server.py`. Then,
> 
> ```
> cd /data/projects/fate/python/fate_flow
> sh service.sh restart
> ```
> 
> Refer to [Fate allinone deployment](https://github.com/FederatedAI/FATE/blob/master/cluster-deploy/doc/Fate-allinone_deployment_guide_install_zh.md)

我是直接按照[standalone-deploy](https://github.com/FederatedAI/FATE/tree/master/standalone-deploy)这里的教程来的，然后想跑一下同态的SecureBoost，在装好以后进入镜像，只执行了如下命令，也出现了类似错误，请问如何解决？
执行的命令：
```
root@66242165a59e:/fatet# cd examples/dsl/v2/homo_secureboost/
root@66242165a59e:/fate/examples/dsl/v2/homo_secureboost# dsl=test_secureboost_train_dsl.json
root@66242165a59e:/fate/examples/dsl/v2/homo_secureboost# runtime_config=test_secureboost_train_binary_conf.json
root@66242165a59e:/fate/examples/dsl/v2/homo_secureboost# flow job submit -c ${runtime_config} -d ${dsl}
```
然后给我返回了这些信息：
```
root@66242165a59e:/fate/examples/dsl/v2/homo_secureboost# flow job submit -c ${runtime_config} -d ${dsl}
{
    "retcode": 100,
    "retmsg": "Fate flow CLI has not been initialized yet or configured incorrectly. Please initialize it before using CLI at the first time. And make sure the address of fate flow server is configured correctly. The configuration file path is: /usr/local/lib/python3.6/site-packages/flow_client/settings.yaml."
}
```
然后我尝试去修改这里的`/usr/local/lib/python3.6/site-packages/flow_client/settings.yaml`，进去发现几乎是空的
```
root@66242165a59e:/fate/examples/dsl/v2/homo_secureboost# cat /usr/local/lib/python3.6/site-packages/flow_client/settings.yaml
api_version: v1
ip:
port:
server_conf_path:
```
这之后我就没什么招了，然后开始翻这里的issue，就找到了这里，这里的[把conf/service_conf.yaml中fateflow的host配置从“127.0.0.1”修改成真实的ip，再重启服务试试](https://github.com/FederatedAI/FATE/issues/2466#issuecomment-768935064)
这一条启发了我去修改对应的位置，像这样：
```
root@66242165a59e:/fate/examples/dsl/v2/homo_secureboost# cat /fate/conf/service_conf.yaml work_mode: 0
use_registry: false
use_deserialize_safe_module: false
fateflow:
  # you must set real ip address, 127.0.0.1 and 0.0.0.0 is not supported
  # host: 127.0.0.1
  host: 192.168.21.177 # 我只改动了这里，我的FATE是部署在VMWare里Ubuntu 18.04 Server 的虚拟机上，网络是桥接模式
  http_port: 9380
  grpc_port: 9360
  # support rollsite/nginx/fateflow as a coordination proxy
  # rollsite support fate on eggroll, use grpc protocol
  # nginx support fate on eggroll and fate on spark, use http or grpc protocol, default is http
  # fateflow support fate on eggroll and fate on spark, use http protocol, but not support exchange network mode
  # 底下的文件我都没有改，太长了就不粘贴过来了
```
然后我回到之前的`/usr/local/lib/python3.6/site-packages/flow_client/settings.yaml`，改成了这样：
```
root@66242165a59e:/fate/examples/dsl/v2/homo_secureboost# cat /usr/local/lib/python3.6/site-packages/flow_client/settings.yaml
api_version: v2
ip: 192.168.21.177
port: 9480
server_conf_path:
```
再执行，就显示这个issue的错误了
```
root@66242165a59e:/fate/examples/dsl/v2/homo_secureboost# flow job submit -c ${runtime_config} -d ${dsl}
{
    "retcode": 100,
    "retmsg": "Connection refused. Please check if the fate flow service is started"
}
```
顺便一提，这是我虚拟机的网络桥接设置，非常简单
![image](https://user-images.githubusercontent.com/45092129/114508006-7ba5e900-9c66-11eb-9079-57d273bbdfb5.png)
![image](https://user-images.githubusercontent.com/45092129/114508128-9aa47b00-9c66-11eb-9b15-2f0b68884a1f.png)
或许是我的操作缺失了哪一步？但是在同态的SecureBoost例子文件夹里的README上也没有再看到更多的信息了。。。
最后，如果需要提供更多的关于复现这个错误的信息，在底下告诉我一声（我现在使用的是1.6.0的Stand-alone压缩包部署）
