### ISSUE TITLE
双机集群单边测试失败

### ISSUE THREAD

**Issue by patricxu** [FederatedAI/FATE#3148]
按照[文档](https://github.com/FederatedAI/FATE/blob/master/cluster-deploy/doc/Fate_cluster_install_guide_ansible.md)的方法配置了guest和host，在host主机运行单边测试成功，而在guest上运行失败。长时间无返回，约5分钟后出现错误信息。

**To Reproduce**
1. 按照文档中的方法配置ansible-nfate-1.6.0/var_files/prod/fate_host。
```
host:
  partyid: 10000
  rollsite:
    enable: True
    ips:
    - 10.113.134.31
    port: 9370
    secure_port: 9371
    pool_size: 600
    max_memory:
    server_secure: False
    client_secure: False
    polling:
      enable: False
    default_rules:
    - name: default
      ip: 10.113.134.32
      port: 9370
      is_secure: False
    rules:
    - name: default
      ip: 10.113.134.31
      port: 9370
    - name: fateflow
      ip: 10.113.134.31
      port: 9360
  clustermanager:
    enable: True
    ips:
    - 10.113.134.31
    port: 4670
    cores_per_node: 16
  nodemanager:
   enable: True
    ips:
    - 10.113.134.31
    - 10.113.134.32
    port: 4671
  eggroll:
    dbname: "eggroll_meta"
    egg: 2
  fate_flow:
    enable: True
    ips:
    - 10.113.134.31
    grpcPort: 9360
    httpPort: 9380
    dbname: "fate_flow"
    proxy: rollsite
  fateboard:
    enable: True
    ips:
    - 10.113.134.31
    port: 8080
    dbname: "fate_flow"
  mysql:
    enable: True
    ips:
    - 10.113.134.31
    port: 3306
    dbuser: "fate"
    dbpasswd: "fate_deV2999"
  zk:
    enable: False
    lists:
    - ip: 10.113.134.31
      port: 2181
    use_acl: false
    user: "fate"
    passwd: "fate"
  servings:
    ip: 10.113.134.31
    port: 8000
                                        
```
2. 以及guest
``` 
guest:
  partyid: 9999
  rollsite:
    enable: True
    ips:
    - 10.113.134.32
    port: 9370
    secure_port: 9371
    pool_size: 600
    max_memory:
    server_secure: False
    client_secure: False
    polling:
      enable: False
    default_rules:
    - name: default
      ip: 10.113.134.31
      port: 9370
      is_secure: False
    rules:
    - name: default
      ip: 10.113.134.32
      port: 9370
    - name: fateflow
      ip: 10.113.134.32
      port: 9360

clustermanager:
    enable: True
    ips:
    - 10.113.134.32
    port: 4670
    cores_per_node: 16
  nodemanager:
    enable: True
    ips:
    - 10.113.134.32
    - 10.113.134.31
    port: 4671
  eggroll:
    dbname: "eggroll_meta"
    egg: 2
  fate_flow:
    enable: True
    ips:
    - 10.113.134.32
    grpcPort: 9360
    httpPort: 9380
    dbname: "fate_flow"
    proxy: rollsite
  fateboard:
    enable: True
    ips:
    - 10.113.134.32
    port: 8080
    dbname: "fate_flow"
  mysql:
    enable: True
    ips:
    - 10.113.134.32
    port: 3306
    dbuser: "fate"
    dbpasswd: "fate_deV2999"
  zk:
    enable: False
    lists:
    - ip: 10.113.134.32
      port: 2181
    use_acl: false
    user: "fate"
    passwd: "fate"
  servings:
    ip: 10.113.134.32
    port: 8000
```
3. 运行nohup  sh ./boot.sh prod -D > logs/boot.log 2>&1 &并查看log显示部署成功
4. 在host的成功运行
```
source /data/projects/fate/bin/init_env.sh
cd /data/projects/fate/examples/toy_example/
python run_toy_example.py 10000 10000 1
```
5. 而在guest上执行一下命令长时间没有返回
```
source /data/projects/fate/bin/init_env.sh
cd /data/projects/fate/examples/toy_example/
python run_toy_example.py 9999 9999 1
```
约5分钟后出现报错信息
![image](https://user-images.githubusercontent.com/9252137/136534824-daaf2c8d-7a85-4793-8175-52d537199462.png)

**Expected behavior**
成功运行guest示例

**Desktop (please complete the following information):**
 - OS: CentOS 7.5
