### ISSUE TITLE
Questions of pipeline example on uploading data and homo logistic regression

### ISSUE THREAD

**Issue by Ichiruchan** [FederatedAI/FATE#3594]
1. First question for homo logistic regression, it is horizontal federated learning. In my opinion, at this time, host and guest have the same data structure(features and labels).  
![image](https://user-images.githubusercontent.com/61850562/148058921-0dbfd493-edc4-462a-9da5-34f2cda78db7.png)
**So if i have more than 2 parties, should I use multi-host homo logistic regression?**
And in the example's config.yaml 
```
parties: # parties default id
  guest:
    - 10000
  host:
    - 9999
    - 10000
  arbiter:
    - 10000
```
**So, can i have an arbiter id different from guests and hosts?**
2. In `pipelien-upload.py` why `  pipeline_upload = PipeLine().set_initiator(role="guest", party_id=guest).set_roles(guest=guest)` only for the guest. For the host? And why it can also upload host data? Maybe you could explain set_initiator in details?

You can answer me in English or Chinese, Thank you very much.
