### ISSUE TITLE
关于V1.9.0版本的standalone部署版本

### ISSUE THREAD

**Issue by oceanqdu** [FederatedAI/FATE#4308]
之前的issue中有提过，V1.9.0版本可以支持Host/Guest 不在一台主机，可使用standalone进行部署并进行交互 #4009
我想问一下需要进行哪些操作才能够使得两台主机使用standalone部署并能够交互？

**Comment by zhihuiwan** [comment]
需要部署通信服务(pulsar或rabbitmq), 然后修改conf/service_conf.yaml:
(1)fateflow命令通道:
a. 直连方式
```yaml
fateflow:
    proxy:
        name: fateflow
        host: xx
        http_port: xx
        grpc_port: xx
```
b. 路由方式
```yaml
fateflow:
    proxy: nginx
```
(2)fate通信通道
