### ISSUE TITLE
两台主机使用standalone进行部署并进行交互

### ISSUE THREAD

**Issue by oceanqdu** [FederatedAI/FATE#4538]
版本1.9.0的更新中提到了，两台不同的主机通过部署standalone版本也能实现联邦。请问具体的实现方式是怎么样的呢？
之前看到有回答说需要部署额外的通讯服务(pulsar或rabbitmq), 然后修改conf/service_conf.yaml。
请帮忙看一下以下步骤可以吗？
1.在两台服务器上成功部署fate 1.9.0 standalone版本。
2、两台主机上全部需要部署通信服务pulsar。（每台主机都部署pulsar的单机模式(standalone)可以吗，部署过程是否可以参考官方文档中的部署方式 https://fate.readthedocs.io/en/latest/zh/deploy/cluster-deploy/doc/fate_on_spark/common/pulsar_deployment_guide/ )
3、修改conf/service_conf.yaml文件，修改内容如下：（请您帮忙看一下yaml文件有无问题）
```
use_registry: false
use_deserialize_safe_module: false
dependent_distribution: false
encrypt_password: false
encrypt_module: fate_arch.common.encrypt_utils#pwdecrypt
private_key:
party_id:
hook_module:
  client_authentication: fate_flow.hook.flow.client_authentication
  site_authentication: fate_flow.hook.flow.site_authentication
  permission: fate_flow.hook.flow.permission
hook_server_name:
authentication:
  client:
    switch: false
    http_app_key:
    http_secret_key:
  site:
    switch: false
permission:
  switch: false
  component: false
  dataset: false
fateflow:
   proxy:
     name: fateflow
     host: xx  #本机IP
     http_port: 9380
     grpc_port: 9360
database:
  name: fate_flow
  user: fate
  passwd: fate
  host: 127.0.0.1
  port: 3306
  max_connections: 100
  stale_timeout: 30
zookeeper:
  hosts:
    - 127.0.0.1:2181
  use_acl: false
  user: fate
  password: fate

default_engines:
  computing: standalone
  federation: pulsar
  storage: standalone
fate_on_standalone:
  standalone:
    cores_per_node: 20
    nodes: 1
fate_on_eggroll:
  clustermanager:
    cores_per_node: 16
    nodes: 1
  rollsite:
    host: 127.0.0.1
    port: 9370
fate_on_spark:
  spark:
    home:
    cores_per_node: 20
    nodes: 2
  linkis_spark:
    cores_per_node: 20
    nodes: 2
    host: 127.0.0.1
    port: 9001
    token_code: MLSS
    python_path: /data/projects/fate/python
  hive:
    host: 127.0.0.1
    port: 10000
    auth_mechanism:
    username:
    password:
  linkis_hive:
    host: 127.0.0.1
    port: 9001
  hdfs:
    name_node: hdfs://fate-cluster
    path_prefix:
  pulsar:
    host: 127.0.0.1
    port: 6650
    mng_port: 8080
    cluster: standalone
    tenant: fl-tenant
    topic_ttl: 30
    # default conf/pulsar_route_table.yaml
    route_table:
    mode: replication
    max_message_size: 1048576
  nginx:
    host: 127.0.0.1
    http_port: 9300
    grpc_port: 9310
# external services
fateboard:
  host: 127.0.0.1
  port: 8080

enable_model_store: false
model_store_address:

  storage: tencent_cos
  Region:
  SecretId:
  SecretKey:
  Bucket:

servings:
  hosts:
    - 127.0.0.1:8000
fatemanager:
  host: 127.0.0.1
  port: 8001
  federatedId: 0
````
假设两台主机同时做完上述步骤之后，他们俩怎么才能实现交互？怎么指定各自的partyid？谁是guest 谁是host？是需要修改conf/pulsar_route_table.yaml文件中的内容吗？仅仅需要修改文件中host和guest的ip就可以吗？，还需其他操作吗？

如果步骤不对能否给出正确的操作步骤，或者给出修改过后的一个有关 conf/service_conf.yaml的demo作为参考？
实在是没有找到有关standalone版本交互的文档或教程，对于一个初学者解决起来有点困难，还希望您能抽出时间帮忙解答一下，十分感谢！
