### ISSUE TITLE
如何部署不同计算后端(eggroll和spark)互联？

### ISSUE THREAD

**Issue by strongman1995** [FederatedAI/FATE#4651]
**Describe the bug**
没有使用教程，关于如何部署不同计算后端（eggroll和spark）互联，v1.9.0说是已经支持了，但是没有任何相关文档，和使用说明。所以想问一下怎么部署呢？能出一份部署文档么？

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zhihuiwan** [comment]
- 先使用ansible部署双边(party_A, party_B)
- 在party_B集群内[部署spark和hadoop](https://github.com/FederatedAI/FATE/blob/master/deploy/cluster-deploy/doc/fate_on_spark/common/hadoop_spark_deployment_guide.zh.md)
- 需保证双方站点使用相同的通信通道(可选rollsite、rabbitmq和pulsar)和命令通道(可选rollsite和nginx)，因为ansible部署的时候已经部署rollsite，此步骤可忽略；
- 修改party_B服务配置: fate/conf/service_conf.yaml
```yaml
default_engines:
  computing: spark
  federation: rollsite  # 可换成rabbitmq或者pulsar,两方需一致
  storage: hdfs
fate_on_spark:
  spark:
    home: /path/to/spark_home # 需要填部署路径
    cores_per_node: 20
    nodes: 2
  hdfs:
    name_node: hdfs://fate-cluster # 需要填hadoop的name_node地址
    path_prefix:
```
- 若想更换命令通道为nginx([nginx部署文档参考](https://github.com/FederatedAI/FATE/blob/master/deploy/cluster-deploy/doc/fate_on_spark/common/nginx_deployment_guide.zh.md))，相关配置修改：
fate/conf/service_conf.yaml
```yaml
fateflow:
  proxy: nginx 
fate_on_spark:
  nginx:
    host: 127.0.0.1
    http_port: 9300
    grpc_port: 9310
```
- 若想更换计算通道为[rabbitmq](https://github.com/FederatedAI/FATE/blob/master/deploy/cluster-deploy/doc/fate_on_spark/common/rabbitmq_deployment_guide.zh.md)或[pulsar](https://github.com/FederatedAI/FATE/blob/master/deploy/cluster-deploy/doc/fate_on_spark/common/pulsar_deployment_guide.zh.md)，相关配置修改：
fate/conf/service_conf.yaml
```yaml
default_engines:
  computing: spark
  federation: rabbitmq # 或pulser
  storage: hdfs
```
另外还需要修改conf/pulsar_route_table.yaml或conf/rabbitmq_route_table.yaml
