### ISSUE TITLE
scripts in `homo_nn_testsuite.yaml` doesn't exist

### ISSUE THREAD

**Issue by asdfsx** [FederatedAI/FATE#5454]
https://github.com/FederatedAI/FATE/blob/cd699d7aee6f6ac7c026119ce801b488afe5079b/examples/pipeline/homo_nn/homo_nn_testsuite.yaml#L36-L40

I think the testsuite should be changed to 
```
tasks:
  homo-nn-binary:
    script: test_nn_binary.py
  homo-nn-multi:
    script: test_nn_multi.py
  homo-nn-regression:
    script: test_nn_regression.py
```
