### ISSUE TITLE
Job计算资源参数不生效

### ISSUE THREAD

**Issue by zchunhai** [FederatedAI/FATE#5471]
版本：FATE 2.0.0

修改Da文件中的cores 参数不生效，后台egg_pair进程数一直为4

```yaml
  conf:
    cores: 8
    computing_partitions: 8
```

请问如何设置Job的计算资源，预计什么时候会有FATE 2.0详细的使用文档呢？
