### ISSUE TITLE
KubeFATE v1.7.0 docker-compose-eggroll.yml 中的挂载文件没有正确配置到有效的路径

### ISSUE THREAD

**Issue by AmazingTai** [FederatedAI/FATE#5612]
**What deployment mode you are use**
1. docker-compose;

**What KubeFATE and FATE version you are using**
v1.7.0 

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.**

 - OS: [centos7] 
 - 配置 [32核/128G/5000G 万兆带宽]

**What happen?**
```
  python:
    image: "federatedai/python:${TAG}"
    environment:
      PYTHONPATH: "$PYTHONPATH:/data/projects/fate/fate/python:/data/projects/fate/eggroll/python:/data/projects/fate/fateflow/python:/data/projects/fate/fate/python/fate_client"
      FATE_PROJECT_BASE: "/data/projects/fate"
    ports:
      - "9360:9360"
      - "9380:9380"
    restart: always
    volumes:
      - shared_dir_federatedml:/data/projects/fate/fate/python/federatedml
      - shared_dir_examples:/data/projects/fate/examples
      - download_dir:/data/projects/fate/python/download_dir
      - ./confs/fate_flow/conf:/data/projects/fate/conf
      ......
```
重点是- ./confs/fate_flow/conf:/data/projects/fate/conf
当我修改./confs/fate_flow/conf/job_default_config.yaml时，我发现提交的任务并没有使用job_default_config中的配置。然后我进入python容器，进入/data/projects/fate/，发现/fateflow/conf还有一个job_default_config.yaml。修改此处配置重启容器后配置生效。
经过修python/fate_flow/db/job_default_config.py改代码打点：
<img width="701" alt="image" src="https://github.com/FederatedAI/KubeFATE/assets/44076220/c22a7db4-fea2-4178-a396-ae3e92d98fff">
在std.log中打印发型使用的是/data/projects/fate/fateflow/conf/job_default_config配置。
![image](https://github.com/FederatedAI/KubeFATE/assets/44076220/9ceb1a34-1b1f-48cb-a85a-a48a29ec99f9)
也就是说docker-compose-eggroll.yml中的- ./confs/fate_flow/conf:/data/projects/fate/conf 并没有正确挂载。应该是：
- ./confs/fate_flow/conf:/data/projects/fate/fateflow/conf

**To Validate**
为了验证猜想，我发现在v1.9：
- ./confs/fate_flow/conf/job_default_config.yaml:/data/projects/fate/fateflow/conf/job_default_config.yaml
是不是修复了这个问题。
