### ISSUE TITLE
fate2.0+spark+lr

### ISSUE THREAD

**Issue by FancyXun** [FederatedAI/FATE#5656]
在进行纵向逻辑回归的时候，一直报这个错

![Screen Shot 2024-07-09 at 18 07 07](https://github.com/FederatedAI/FATE/assets/18592060/17718a3d-9259-45f1-98ff-28f8d078f776)

如下是我的yaml文件
```
dag:
  parties:
  - party_id: ['9999']
    role: guest
  - party_id: ['10000']
    role: host
  - party_id: ['10000']
    role: arbiter
  party_tasks:
    guest_9999:
      parties:
      - party_id: ['9999']
        role: guest
      tasks:
        reader_0:
          parameters: {name: breast_hetero_mini_guest, namespace: experiment}
    host_10000:
      parties:
      - party_id: ['10000']
        role: host
      tasks:
        reader_0:
          parameters: {name: breast_hetero_mini_host, namespace: experiment}
  stage: train
  tasks:
    lr_0:
      component_ref: coordinated_lr
      dependent_tasks: [psi_0]
      inputs:
        data:
          train_data:
            task_output_artifact:
              output_artifact_key: output_data
              parties:
              - party_id: ['9999']
                role: guest
              - party_id: ['10000']
                role: host
              producer_task: psi_0
        model: {}
      parameters:
        batch_size: null
        early_stop: diff
        epochs: 3
        floating_point_precision: 23
        init_param: {fit_intercept: true, method: random_uniform, random_state: 42}
        learning_rate_scheduler:
          method: linear
          scheduler_params: {start_factor: 0.7, total_iters: 100}
        optimizer:
          alpha: 0.001
          method: rmsprop
          optimizer_params: {lr: 0.1}
          penalty: l2
        output_cv_data: true
        threshold: 0.5
        tol: 0.0001
    psi_0:
      component_ref: psi
      dependent_tasks: [reader_0]
      inputs:
        data:
          input_data:
            task_output_artifact:
              output_artifact_key: output_data
              parties:
              - party_id: ['9999']
                role: guest
              - party_id: ['10000']
                role: host
              producer_task: reader_0
      parameters: {}
      parties:
      - party_id: ['9999']
        role: guest
      - party_id: ['10000']
        role: host
      stage: default
    reader_0:
      component_ref: reader
      parties:
        - party_id:
            - '9999'
          role: guest
        - party_id:
            - '10000'
          role: host
      stage: default
schema_version: 2.0.0
```
