### ISSUE TITLE
验证阶段读不到模型的输出？

### ISSUE THREAD

**Issue by FancyXun** [FederatedAI/FATE#5662]
YAML文件如下：
```
dag:
  parties:
  - party_id: ['9999']
    role: guest
  - party_id: ['10000']
    role: host
  party_tasks:
    guest_9999:
      parties:
      - party_id: ['9999']
        role: guest
      tasks:
        reader_0:
          parameters: {name: breast_hetero_guest, namespace: experiment}
    host_10000:
      parties:
      - party_id: ['10000']
        role: host
      tasks:
        reader_0:
          parameters: {name: breast_hetero_host, namespace: experiment}
  stage: train
  tasks:
    eval_0:
      component_ref: evaluation
      dependent_tasks: [sbt_0]
      inputs:
        data:
          input_data:
            task_output_artifact:
            - output_artifact_key: train_data_output
              parties:
              - party_id: ['9999']
                role: guest
              producer_task: sbt_0
      parameters:
        label_column_name: null
        metrics: [auc]
        predict_column_name: null
      parties:
      - party_id: ['9999']
        role: guest
      stage: default

    psi_0:
      component_ref: psi
      dependent_tasks: [reader_0]
      inputs:
        data:
          input_data:
            task_output_artifact:
              output_artifact_key: output_data
              parties:
              - party_id: ['9999']
                role: guest
              - party_id: ['10000']
                role: host
              producer_task: reader_0
      parameters: {}
      stage: default
    reader_0:
      component_ref: reader
      parameters: {}
      stage: default
    sbt_0:
      component_ref: hetero_secureboost
      dependent_tasks: [psi_0]
      inputs:
        data:
          cv_data:
            task_output_artifact:
              output_artifact_key: output_data
              parties:
              - party_id: ['9999']
                role: guest
              - party_id: ['10000']
                role: host
              producer_task: psi_0
        model: {}
      parameters:
        cv_param: {n_splits: 3}
        gh_pack: true
        goss: false
        goss_start_iter: 0
        he_param: {key_length: 1024, kind: paillier}
        hist_sub: true
        l1: 0
        l2: 0.1
        learning_rate: 0.3
        max_bin: 32
        max_depth: 2
        min_child_weight: 1
        min_impurity_split: 0.01
        min_leaf_node: 1
        min_sample_split: 2
        num_class: 2
        num_trees: 2
        objective: binary:bce
        other_rate: 0.1
        split_info_pack: true
        top_rate: 0.2
      stage: cross_validation
schema_version: 2.0.0
```

提交后

<img width="1628" alt="Screen Shot 2024-07-11 at 16 06 48" src="https://github.com/FederatedAI/FATE/assets/18592060/854e97c8-0a23-41e1-b6a4-8f6df22bb336">

报错如下：
```
[ERROR][2024-07-11 07:54:39,269][585110][_wraps.run][line:92]: Get data artifacts failed: {'job_id': '202407110739162543270', 'role': 'guest', 'party_id': '9999', 'task_name': 'sbt_0', 'output_key': 'train_data_output'}, response: {"code":2005,"message":"failed"}
[ERROR][2024-07-11 07:54:39,269][585110][_wraps.run][line:92]: Get data artifacts failed: {'job_id': '202407110739162543270', 'role': 'guest', 'party_id': '9999', 'task_name': 'sbt_0', 'output_key': 'train_data_output'}, response: {"code":2005,"message":"failed"}
```

感觉像是sbt没有输出模型吗？所以fate-server没找到？这个yaml文件我也是基于 https://github.com/FederatedAI/FATE/blob/v2.0.0/examples/pipeline/hetero_secureboost/test_hetero_sbt_binary.py 这个生成的

**Comment by talkingwallace** [comment]
sbt是有输出模型的 你提交任务的文件是什么样子的？这个看着是intput/output相关的配置配置错误了

**Comment by FancyXun** [comment]
> sbt是有输出模型的 你提交任务的文件是什么样子的？这个看着是intput/output相关的配置配置错误了

提交的就是我图中写的yaml文件 @talkingwallace

**Comment by talkingwallace** [comment]
我看到你跑的是cv模式 cv的话是没有数据输出的

**Comment by FancyXun** [comment]
我不跑cv模式，会有如下的Bug，看起来是我更新了fate-spark到2.1以后的问题 
![Screen Shot 2024-07-12 at 12 05 55](https://github.com/user-attachments/assets/b2262598-de0d-41d2-8202-9488c29d8332)

**Comment by FancyXun** [comment]
因为现在没有2.1的k8s镜像，但是在2.0会有spark的rdd 分区的问题，所以我将一部分修复这个rdd分区的代码替换了，具体详情可以在这里看到 https://github.com/FederatedAI/FATE/issues/5656   @talkingwallace

**Comment by FancyXun** [comment]
> 我不跑cv模式，会有如下的Bug，看起来是我更新了fate-spark到2.1以后的问题 ![Screen Shot 2024-07-12 at 12 05 55](https://private-user-images.githubusercontent.com/18592060/348122204-b2262598-de0d-41d2-8202-9488c29d8332.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NjQ2MzYsIm5iZiI6MTcyMDc2NDMzNiwicGF0aCI6Ii8xODU5MjA2MC8zNDgxMjIyMDQtYjIyNjI1OTgtZGUwZC00MWQyLTgyMDItOTQ4OGMyOWQ4MzMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA2MDUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNmFkN2NlZTViYmUxZGI1MzU1NThlYTlkYzc4YmI0MjQ2NzNhMjExNjU2MzM3MDBjMjUxMjg0YzA5NTM2NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CdBuT5yqcG4mjNrNjga4xyHb7eH1iVRQP3hU9zyRi3A)

对应的yaml文件如下：
```
dag:
  parties:
  - party_id: ['9999']
    role: guest
  - party_id: ['10000']
    role: host
  party_tasks:
    guest_9999:
      parties:
      - party_id: ['9999']
        role: guest
      tasks:
        reader_0:
          parameters: {name: breast_hetero_guest, namespace: experiment}
    host_10000:
      parties:
      - party_id: ['10000']
        role: host
      tasks:
        reader_0:
          parameters: {name: breast_hetero_host, namespace: experiment}
  stage: train
  tasks:
    eval_0:
      component_ref: evaluation
      dependent_tasks: [sbt_0]
      inputs:
        data:
          input_data:
            task_output_artifact:
            - output_artifact_key: train_data_output
              parties:
              - party_id: ['9999']
                role: guest
              producer_task: sbt_0
      parameters:
        label_column_name: null
        metrics: [auc]
        predict_column_name: null
      parties:
      - party_id: ['9999']
        role: guest
      stage: default

    psi_0:
      component_ref: psi
      dependent_tasks: [reader_0]
      inputs:
        data:
          input_data:
            task_output_artifact:
              output_artifact_key: output_data
              parties:
              - party_id: ['9999']
                role: guest
              - party_id: ['10000']
                role: host
              producer_task: reader_0
      parameters: {}
      stage: default
    reader_0:
      component_ref: reader
      parameters: {}
      stage: default
    sbt_0:
      component_ref: hetero_secureboost
      dependent_tasks: [ psi_0 ]
      inputs:
        data:
          train_data:
            task_output_artifact:
              output_artifact_key: output_data
              parties:
                - party_id: [ '9999' ]
                  role: guest
                - party_id: [ '10000' ]
                  role: host
              producer_task: psi_0
        model: { }
      parameters:
        gh_pack: true
        goss: true
        goss_start_iter: 0
        he_param: { key_length: 1024, kind: paillier }
        hist_sub: true
        l1: 0
        l2: 0.1
        learning_rate: 0.3
        max_bin: 32
        max_depth: 2
        min_child_weight: 1
        min_impurity_split: 0.01
        min_leaf_node: 1
        min_sample_split: 2
        num_class: 2
        num_trees: 2
        objective: binary:bce
        other_rate: 0.1
        split_info_pack: true
        top_rate: 0.2
schema_version: 2.0.0
```
